email:
  server: "imap.gmail.com"
  username: "projecttester454@gmail.com"
  password: "Project123"
  folder: "INBOX"

ftp:
  host: "sftp.target.com"
  port: 22
  username: "ftpuser"
  password: "secret"
  target_dir: "/upload"

security:
  passwords:
    "customerA": "pass123"
    "customerB": "bankpass"

output:
  dir: "./output"
  schema: ["Invoice No", "Amount", "Date", "UTR", "Customer"]

log:
  path: "./data/logs/eliza.log"