email:
  server: "imap.gmail.com"
  username: "projecttester454@gmail.com"
  password: "woru fqlr xuaa vrbf"
  folder: "INBOX"

ftp:
  host: "127.0.0.1"
  port: 22
  username: "tushar" # Use your actual Linux username
  password: "" #enter password
  target_dir: "/home/tushar/uploads" # Use the full path to your new folder

security:
  passwords:
    "customerA": "pass123"
    "customerB": "bankpass"

output:
  dir: "./output"
  schema: ["Invoice No", "Amount", "Date", "UTR", "Customer"]

log:
  path: "./data/logs/eliza.log"